baseurl = "https://example.org/"
languageCode = "ru"
title = "Steam - a minimal theme for Hugo"
theme = "hugo-steam-theme"
disqusShortname = "spf13"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10
publishDir = "docs"

[params]
	title = "Вадим Логинов"
	subtitle = "Убегая от говнокода"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Vadim Loginov"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"

	# Link your social networks (optional)
	location = ""
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "vloginov"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "читать"
	backtotopStr = "На главную"
	shareStr = "Поделиться"
	pageNotFoundTitle = "404 - Страница не найдена"
